import { Router } from 'express';
import bcrypt from 'bcryptjs';
import crypto from 'node:crypto';
import { z } from 'zod';
import { Company } from '../models/company.model.js';
import { User } from '../models/user.model.js';
import { ActionToken, RefreshToken } from '../models/token.model.js';
import { validate } from '../middleware/validate.js';
import { authenticate } from '../middleware/auth.js';
import { asyncHandler } from '../shared/async-handler.js';
import { AppError } from '../shared/errors.js';
import { publicId } from '../shared/id.js';
import { ok } from '../shared/response.js';
import { changePasswordSchema, forgotSchema, loginSchema, refreshSchema, registerSchema, resetSchema } from '../validators/auth.validator.js';
import { consumePasswordReset, createActionToken, login, publicUser, rotateRefreshToken } from '../services/auth.service.js';

export const authRouter = Router();
authRouter.post('/register', validate(registerSchema), asyncHandler(async (req, res) => {
  const b = req.body;
  if (await User.exists({ email: b.email.toLowerCase() })) throw new AppError(409, 'Email is already registered');
  const count = await Company.countDocuments();
  const companyId = `KP-C-${String(843 + count).padStart(5, '0')}`;
  const initials = b.companyName.split(/\s+/).slice(0, 2).map((x: string) => x[0]).join('').toUpperCase();
  const initialTopUp = b.initialTopUp ?? b.initialRecharge ?? 0;
  const company = await Company.create({ companyId, name: b.companyName, initials, category: b.category ?? b.businessCategory, gstNumber: b.gstNumber ?? b.gst, panNumber: b.panNumber, website: b.website, email: b.email, phone: b.phone, contactName: b.contactName, address: b.address, state: b.state, city: b.city, pincode: b.pincode, walletBalance: initialTopUp, totalRecharged: initialTopUp });
  await User.create({ publicId: publicId('u'), company: company._id, name: b.contactName, email: b.email, phone: b.phone, passwordHash: await bcrypt.hash(b.password, 12), role: 'root', roleLabel: 'Company Root', permissions: ['all'], status: 'active' });
  ok(res, { companyId }, 'Registration submitted for approval', 201);
}));
authRouter.post('/login', validate(loginSchema), asyncHandler(async (req, res) => ok(res, await login(req.body.email, req.body.password, req.body.companyId, { ip: req.ip, userAgent: req.get('user-agent') }))));
authRouter.post('/refresh', validate(refreshSchema), asyncHandler(async (req, res) => ok(res, await rotateRefreshToken(req.body.refreshToken, { ip: req.ip, userAgent: req.get('user-agent') }))));
authRouter.post('/logout', asyncHandler(async (req, res) => { const token = req.body?.refreshToken as string | undefined; if (token) await RefreshToken.updateOne({ tokenHash: crypto.createHash('sha256').update(token).digest('hex') }, { revokedAt: new Date() }); ok(res, null, 'Logged out'); }));
authRouter.get('/me', authenticate, asyncHandler(async (req, res) => ok(res, await publicUser(req.user!))));
authRouter.post('/forgot-password', validate(forgotSchema), asyncHandler(async (req, res) => { const user = await User.findOne({ email: req.body.email, deletedAt: null }); const resetToken = user ? await createActionToken(user._id, 'password-reset') : undefined; ok(res, process.env.NODE_ENV !== 'production' ? { resetToken } : null, 'If that account exists, reset instructions have been generated'); }));
authRouter.post('/reset-password', validate(resetSchema), asyncHandler(async (req, res) => { await consumePasswordReset(req.body.token, req.body.password); ok(res, null, 'Password reset successfully'); }));
authRouter.post('/change-password', authenticate, validate(changePasswordSchema), asyncHandler(async (req, res) => { const user = await User.findById(req.user!._id).select('+passwordHash'); if (!user || !(await bcrypt.compare(req.body.currentPassword, user.passwordHash))) throw new AppError(400, 'Current password is incorrect'); user.passwordHash = await bcrypt.hash(req.body.newPassword, 12); user.passwordChangedAt = new Date(); await user.save(); await RefreshToken.updateMany({ user: user._id, revokedAt: null }, { revokedAt: new Date() }); ok(res, null, 'Password changed successfully'); }));
authRouter.post('/accept-invite', validate(z.object({ body: z.object({ token: z.string().min(20), password: z.string().min(8) }), query: z.any(), params: z.any() })), asyncHandler(async (req, res) => { const tokenHash = crypto.createHash('sha256').update(req.body.token).digest('hex'); const user = await User.findOne({ invitationTokenHash: tokenHash, invitationExpiresAt: { $gt: new Date() }, status: 'invited' }).select('+invitationTokenHash'); if (!user) throw new AppError(400, 'Invitation is invalid or expired'); user.passwordHash = await bcrypt.hash(req.body.password, 12); user.status = 'active'; user.invitationTokenHash = undefined; user.invitationExpiresAt = undefined; await user.save(); ok(res, await publicUser(user), 'Invitation accepted'); }));
authRouter.post('/email-verification/request', authenticate, asyncHandler(async (req, res) => { const verificationToken = await createActionToken(req.user!._id, 'email-verification', 60); ok(res, process.env.NODE_ENV !== 'production' ? { verificationToken } : null, 'Email verification instructions generated'); }));
authRouter.post('/email-verification/verify', validate(z.object({ body: z.object({ token: z.string().min(20) }), query: z.any(), params: z.any() })), asyncHandler(async (req, res) => { const record = await ActionToken.findOne({ tokenHash: crypto.createHash('sha256').update(req.body.token).digest('hex'), purpose: 'email-verification', usedAt: null, expiresAt: { $gt: new Date() } }); if (!record) throw new AppError(400, 'Verification token is invalid or expired'); await User.updateOne({ _id: record.user }, { emailVerifiedAt: new Date() }); record.usedAt = new Date(); await record.save(); ok(res, null, 'Email verified'); }));
authRouter.post('/otp/request', validate(forgotSchema), asyncHandler(async (req, res) => { const user = await User.findOne({ email: req.body.email.toLowerCase(), deletedAt: null }); let otp: string | undefined; if (user) { otp = String(crypto.randomInt(100000, 1000000)); await ActionToken.create({ user: user._id, purpose: 'otp', tokenHash: crypto.createHash('sha256').update(otp).digest('hex'), expiresAt: new Date(Date.now() + 10 * 60_000) }); } ok(res, process.env.NODE_ENV !== 'production' ? { otp } : null, 'If that account exists, an OTP has been generated'); }));
authRouter.post('/otp/verify', validate(z.object({ body: z.object({ email: z.email(), otp: z.string().regex(/^\d{6}$/) }), query: z.any(), params: z.any() })), asyncHandler(async (req, res) => { const user = await User.findOne({ email: req.body.email.toLowerCase(), deletedAt: null }); if (!user) throw new AppError(400, 'OTP is invalid or expired'); const record = await ActionToken.findOne({ user: user._id, purpose: 'otp', tokenHash: crypto.createHash('sha256').update(req.body.otp).digest('hex'), usedAt: null, expiresAt: { $gt: new Date() } }); if (!record) throw new AppError(400, 'OTP is invalid or expired'); record.usedAt = new Date(); await record.save(); ok(res, { verified: true }, 'OTP verified'); }));
