import { Router } from 'express';
import { z } from 'zod';
import { Campaign } from '../models/campaign.model.js';
import { Company } from '../models/company.model.js';
import { User } from '../models/user.model.js';
import { authorize } from '../middleware/auth.js';
import { validate } from '../middleware/validate.js';
import { asyncHandler } from '../shared/async-handler.js';
import { AppError } from '../shared/errors.js';
import { ok } from '../shared/response.js';

export const companyRouter = Router();
companyRouter.get('/', authorize('companies'), asyncHandler(async (req, res) => { const page = Math.max(1, Number(req.query.page) || 1), limit = Math.min(100, Math.max(1, Number(req.query.limit) || 20)); const filter: Record<string, unknown> = { deletedAt: null }; if (req.query.status && req.query.status !== 'all') filter.status = req.query.status; if (req.query.search) filter.$text = { $search: req.query.search }; const [companies, total] = await Promise.all([Company.find(filter).sort({ createdAt: -1 }).skip((page - 1) * limit).limit(limit).lean(), Company.countDocuments(filter)]); const ids = companies.map((c) => c._id); const [campaigns, employees] = await Promise.all([Campaign.aggregate([{ $match: { company: { $in: ids }, deletedAt: null } }, { $group: { _id: '$company', count: { $sum: 1 } } }]), User.aggregate([{ $match: { company: { $in: ids }, deletedAt: null } }, { $group: { _id: '$company', count: { $sum: 1 } } }])]); const counts = (rows: { _id: unknown; count: number }[]) => new Map(rows.map((x) => [String(x._id), x.count])); const cc = counts(campaigns), ec = counts(employees); ok(res, companies.map((c) => ({ id: String(c._id), name: c.name, companyId: c.companyId, category: c.category, contactName: c.contactName, email: c.email, phone: c.phone, state: c.state, status: c.status, registeredAt: c.createdAt, campaigns: cc.get(String(c._id)) ?? 0, walletBalance: c.walletBalance, employees: ec.get(String(c._id)) ?? 0 })), undefined, 200, { total, page, limit }); }));
companyRouter.get('/export/csv', authorize('companies'), asyncHandler(async (_req, res) => { const rows = await Company.find({ deletedAt: null }).sort({ createdAt: -1 }).lean(); const esc = (v: unknown) => `"${String(v ?? '').replaceAll('"','""')}"`; const csv = [['Company ID','Name','Category','Contact','Email','Phone','State','Status','Wallet','Registered'], ...rows.map((c) => [c.companyId,c.name,c.category,c.contactName,c.email,c.phone,c.state,c.status,c.walletBalance,c.createdAt.toISOString()])].map((r) => r.map(esc).join(',')).join('\n'); res.type('text/csv').attachment('krishipath-companies.csv').send(`\uFEFF${csv}`); }));
companyRouter.get('/:id', authorize('companies'), asyncHandler(async (req, res) => { const id = String(req.params.id); const c = await Company.findOne({ $or: [{ companyId: id }, { _id: /^[a-f\d]{24}$/i.test(id) ? id : undefined }], deletedAt: null }).lean(); if (!c) throw new AppError(404, 'Company not found'); ok(res, c); }));
companyRouter.patch('/:id/status', authorize('companies'), validate(z.object({ body: z.object({ status: z.enum(['pending', 'approved', 'suspended']) }), query: z.any(), params: z.any() })), asyncHandler(async (req, res) => { const patch: Record<string, unknown> = { status: req.body.status }; if (req.body.status === 'approved') Object.assign(patch, { verified: true, approvedAt: new Date(), approvedBy: req.user!._id }); const c = await Company.findOneAndUpdate({ companyId: req.params.id, deletedAt: null }, patch, { new: true, runValidators: true }); if (!c) throw new AppError(404, 'Company not found'); ok(res, c, `Company ${req.body.status}`); }));
