import { Router } from 'express';
import { Campaign } from '../models/campaign.model.js';
import { Company } from '../models/company.model.js';
import { Lead } from '../models/lead.model.js';
import { Transaction } from '../models/wallet.model.js';
import { asyncHandler } from '../shared/async-handler.js';
import { AppError } from '../shared/errors.js';
import { ok } from '../shared/response.js';

export const dashboardRouter = Router();
dashboardRouter.get('/kpi', asyncHandler(async (req, res) => { const company = await Company.findById(req.user!.company).lean(); if (!company) throw new AppError(404, 'Company not found'); const campaigns = await Campaign.find({ company: company._id, deletedAt: null }).lean(); const sum = (key: 'reach'|'videoViews'|'quizCompletions'|'brochureDownloads'|'callbackRequests'|'walletUsed') => campaigns.reduce((a, c) => a + Number(c[key]), 0); const totalReach = sum('reach'), videoViews = sum('videoViews'), quizzes = sum('quizCompletions'); const [totalFarmers, rewardsAgg] = await Promise.all([Lead.countDocuments({ company: company._id, deletedAt: null }), Transaction.aggregate([{ $match: { company: company._id, type: 'reward-distributed' } }, { $group: { _id: null, total: { $sum: { $abs: '$amount' } } } }])]); const start = new Date(); start.setHours(0,0,0,0); const today = await Transaction.aggregate([{ $match: { company: company._id, createdAt: { $gte: start }, amount: { $lt: 0 } } }, { $group: { _id: null, total: { $sum: { $abs: '$amount' } } } }]); ok(res, { walletBalance: company.walletBalance, todaySpend: today[0]?.total ?? 0, activeCampaigns: campaigns.filter((c) => c.status === 'active').length, totalReach, videoCompletionRate: totalReach ? Math.round(videoViews / totalReach * 100) : 0, quizCompletionRate: videoViews ? Math.round(quizzes / videoViews * 100) : 0, brochureDownloads: sum('brochureDownloads'), callbackRequests: sum('callbackRequests'), avgROI: Number(company.totalSpent) ? Number((totalReach / Number(company.totalSpent)).toFixed(1)) : 0, totalFarmers, rewardsDistributed: rewardsAgg[0]?.total ?? 0 }); }));
dashboardRouter.get('/metrics', asyncHandler(async (req, res) => { const months = Math.min(24, Math.max(1, Number(String(req.query.range ?? '6').replace(/\D/g, '')) || 6)); const since = new Date(); since.setMonth(since.getMonth() - months + 1, 1); since.setHours(0,0,0,0); const rows = await Campaign.aggregate([{ $match: { company: req.user!.company, deletedAt: null, createdAt: { $gte: since } } }, { $group: { _id: { y: { $year: '$createdAt' }, m: { $month: '$createdAt' } }, reach: { $sum: '$reach' }, videoViews: { $sum: '$videoViews' }, quizCompletions: { $sum: '$quizCompletions' }, brochureDownloads: { $sum: '$brochureDownloads' }, callbacks: { $sum: '$callbackRequests' }, spend: { $sum: '$walletUsed' } } }, { $sort: { '_id.y': 1, '_id.m': 1 } }]); ok(res, rows.map((r) => ({ month: new Date(r._id.y, r._id.m - 1).toLocaleString('en', { month: 'short' }), ...r, roi: r.spend ? Number((r.reach / r.spend).toFixed(1)) : 0, _id: undefined }))); }));
dashboardRouter.get('/reward-breakdown', asyncHandler(async (req, res) => { const campaigns = await Campaign.find({ company: req.user!.company, deletedAt: null }).lean(); const value = (reward: 'videoReward'|'quizReward'|'brochureReward'|'callbackReward', metric: 'videoViews'|'quizCompletions'|'brochureDownloads'|'callbackRequests') => campaigns.reduce((a,c) => a + c[reward] * c[metric], 0); ok(res, [{ name: 'Video Rewards', value: value('videoReward','videoViews'), color: '#2E7D32' }, { name: 'Quiz Rewards', value: value('quizReward','quizCompletions'), color: '#F9A825' }, { name: 'Brochure Rewards', value: value('brochureReward','brochureDownloads'), color: '#039BE5' }, { name: 'Callback Rewards', value: value('callbackReward','callbackRequests'), color: '#FB8C00' }]); }));
