import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import compression from 'compression';
import morgan from 'morgan';
import rateLimit from 'express-rate-limit';
import swaggerUi from 'swagger-ui-express';
import { env } from './config/env.js';
import { swaggerSpec } from './config/swagger.js';
import { authenticate } from './middleware/auth.js';
import { auditMutations, requestContext } from './middleware/audit.js';
import { errorHandler, notFound } from './middleware/error.js';
import { authRouter } from './routes/auth.routes.js';
import { campaignRouter } from './routes/campaign.routes.js';
import { leadRouter } from './routes/lead.routes.js';
import { walletRouter } from './routes/wallet.routes.js';
import { notificationRouter } from './routes/notification.routes.js';
import { dashboardRouter } from './routes/dashboard.routes.js';
import { analyticsRouter } from './routes/analytics.routes.js';
import { companyRouter } from './routes/company.routes.js';
import { teamRouter } from './routes/team.routes.js';
import { settingsRouter } from './routes/settings.routes.js';
import { uploadRouter } from './routes/upload.routes.js';
import { auditRouter } from './routes/audit.routes.js';

export const app = express();
app.set('trust proxy', 1);
app.disable('x-powered-by');
app.use(requestContext);
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin(origin, cb) { if (!origin || env.corsOrigins.includes(origin)) return cb(null, true); cb(new Error('Origin is not allowed by CORS')); }, credentials: true, exposedHeaders: ['x-request-id','content-disposition'] }));
app.use(compression());
app.use(express.json({ limit: '2mb' }));
app.use(express.urlencoded({ extended: true, limit: '2mb' }));
app.use(morgan(env.NODE_ENV === 'production' ? 'combined' : 'dev'));
app.use(rateLimit({ windowMs: 15 * 60_000, limit: env.NODE_ENV === 'test' ? 10_000 : 500, standardHeaders: 'draft-8', legacyHeaders: false }));
app.use(`${env.API_PREFIX}/auth`, rateLimit({ windowMs: 15 * 60_000, limit: env.NODE_ENV === 'test' ? 10_000 : 30 }), authRouter);
app.get('/health', (_req, res) => res.json({ success: true, data: { status: 'ok', uptime: process.uptime(), timestamp: new Date().toISOString() } }));
app.use('/docs', swaggerUi.serve, swaggerUi.setup(swaggerSpec));
app.get('/openapi.json', (_req, res) => res.json(swaggerSpec));
app.use(env.API_PREFIX, authenticate, auditMutations);
app.use(`${env.API_PREFIX}/campaigns`, campaignRouter);
app.use(`${env.API_PREFIX}/leads`, leadRouter);
app.use(`${env.API_PREFIX}/wallet`, walletRouter);
app.use(`${env.API_PREFIX}/notifications`, notificationRouter);
app.use(`${env.API_PREFIX}/dashboard`, dashboardRouter);
app.use(`${env.API_PREFIX}/analytics`, analyticsRouter);
app.use(`${env.API_PREFIX}/companies`, companyRouter);
app.use(`${env.API_PREFIX}/team`, teamRouter);
app.use(`${env.API_PREFIX}/settings`, settingsRouter);
app.use(`${env.API_PREFIX}/uploads`, uploadRouter);
app.use(`${env.API_PREFIX}/audit-logs`, auditRouter);
app.use(notFound);
app.use(errorHandler);
