export const PERMISSIONS = {
  // Mandi Operations
  MANDI_VIEW: 'MANDI_VIEW',
  MANDI_CREATE: 'MANDI_CREATE',
  MANDI_EDIT: 'MANDI_EDIT',
  MANDI_DELETE: 'MANDI_DELETE',
  MANDI_DUPLICATE: 'MANDI_DUPLICATE',

  // Crop Catalog
  CROP_VIEW: 'CROP_VIEW',
  CROP_CREATE: 'CROP_CREATE',
  CROP_EDIT: 'CROP_EDIT',

  // Prices
  PRICE_VIEW: 'PRICE_VIEW',
  PRICE_UPDATE: 'PRICE_UPDATE',
  PRICE_APPROVE: 'PRICE_APPROVE',

  // Users & Roles
  USER_VIEW: 'USER_VIEW',
  USER_CREATE: 'USER_CREATE',
  USER_EDIT: 'USER_EDIT',
  USER_BAN: 'USER_BAN',

  // Localization
  LOC_VIEW: 'LOC_VIEW',
  LOC_EDIT: 'LOC_EDIT',
  LOC_APPROVE: 'LOC_APPROVE',

  // System
  SYS_VIEW: 'SYS_VIEW',
  SYS_EDIT: 'SYS_EDIT',
  SYS_FLAG_EDIT: 'SYS_FLAG_EDIT',

  // Marketing & Growth
  MARKETING_VIEW: 'MARKETING_VIEW',
  MARKETING_EDIT: 'MARKETING_EDIT',

  // Intelligence & Analytics
  ANALYTICS_VIEW: 'ANALYTICS_VIEW',
};

// Default roles mapping for the UI (Super Admin implicitly has everything)
export const ROLE_PERMISSIONS = {
  MANDI_ADMIN: [
    PERMISSIONS.MANDI_VIEW,
    PERMISSIONS.MANDI_EDIT,
    PERMISSIONS.CROP_VIEW,
    PERMISSIONS.PRICE_VIEW,
    PERMISSIONS.PRICE_UPDATE,
  ],
  CONTENT_MOD: [
    PERMISSIONS.LOC_VIEW,
    PERMISSIONS.LOC_EDIT,
    PERMISSIONS.CROP_VIEW,
  ]
};
