export interface RoleTemplate {
  name: string;
  description: string;
  keys: string[];
}

export class RoleTemplates {
  public static list(): RoleTemplate[] {
    return [
      {
        name: "Super Admin",
        description: "Full platform access",
        keys: [
          "auth.session.read",
          "auth.session.revoke",
          "users.farmer.read",
          "users.farmer.update",
          "users.creator.read",
          "users.creator.update",
          "users.trader.read",
          "users.trader.update",
          "users.company.read",
          "users.company.update",
          "users.admin.manage",
          "mandi.mandi.read",
          "mandi.mandi.manage",
          "mandi.product.manage",
          "mandi.price.manage",
          "content.video.upload",
          "content.video.moderate",
          "content.market_insight.manage",
          "content.scheme.manage",
          "content.poll.manage",
          "gamification.points.manage",
          "gamification.badges.manage",
          "campaign.campaign.create",
          "campaign.campaign.approve",
          "campaign.wallet.manage",
          "campaign.lead.manage",
          "settings.read",
          "settings.update",
          "notify.notification.send",
          "audit.log.read",
          "platform.logs.read",
          "roles.create",
          "roles.read",
          "roles.update",
          "roles.delete",
          "roles.permission.assign",
        ],
      },
      {
        name: "Admin",
        description: "Platform administration",
        keys: [
          "users.farmer.read",
          "users.farmer.update",
          "users.creator.read",
          "users.creator.update",
          "users.trader.read",
          "users.trader.update",
          "users.company.read",
          "users.company.update",
          "mandi.mandi.read",
          "mandi.mandi.manage",
          "mandi.product.manage",
          "mandi.price.manage",
          "content.video.moderate",
          "content.market_insight.manage",
          "content.scheme.manage",
          "content.poll.manage",
          "gamification.points.manage",
          "gamification.badges.manage",
          "campaign.campaign.approve",
          "campaign.wallet.manage",
          "campaign.lead.manage",
          "settings.read",
          "settings.update",
          "notify.notification.send",
          "audit.log.read",
          "roles.read",
        ],
      },
      {
        name: "Moderator",
        description: "Content moderation",
        keys: [
          "content.video.moderate",
          "users.farmer.read",
          "users.creator.read",
          "users.trader.read",
        ],
      },
      {
        name: "Finance",
        description: "Finance and wallet operations",
        keys: [
          "campaign.wallet.manage",
          "gamification.points.manage",
          "users.company.read",
        ],
      },
      {
        name: "Operations",
        description: "Data entry and market insights",
        keys: [
          "mandi.mandi.read",
          "mandi.mandi.manage",
          "mandi.product.manage",
          "content.market_insight.manage",
          "content.scheme.manage",
          "content.poll.manage",
        ],
      },
      {
        name: "Support",
        description: "Customer support",
        keys: [
          "users.farmer.read",
          "users.trader.read",
          "users.creator.read",
          "users.company.read",
          "notify.notification.send",
          "settings.read",
        ],
      },
      {
        name: "Agri Company",
        description: "Agri-input company running campaigns",
        keys: [
          "users.company.read",
          "users.company.update",
          "campaign.campaign.create",
          "campaign.wallet.manage",
          "campaign.lead.manage",
          "settings.read",
          "content.poll.manage",
        ],
      },
      {
        name: "Trader",
        description: "Mandi trader managing product prices",
        keys: [
          "users.trader.read",
          "users.trader.update",
          "mandi.mandi.read",
          "mandi.price.manage",
          "settings.read",
        ],
      },
      {
        name: "Farmer",
        description: "KrishiPath farmer",
        keys: [
          "users.farmer.read",
          "users.farmer.update",
          "mandi.mandi.read",
          "settings.read",
          "content.video.upload",
        ],
      },
      {
        name: "Creator",
        description: "KrishiPath content creator (extends Farmer)",
        keys: [
          "users.farmer.read",
          "users.farmer.update",
          "users.creator.read",
          "users.creator.update",
          "mandi.mandi.read",
          "settings.read",
          "content.video.upload",
        ],
      },
    ];
  }
}
